### ISSUE TITLE
Slugification of capital umlauts can be improved

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#174]
For example, in the filename template a capital Ü is transliterated to UE, which means that e.g. Überwacher is transliterated to UEberwacher.

Ideas: either take some explicit care of it, or slugify to a complete lower-case string.

**Comment by jjeising** [comment]
Conversion for Umlauts is currently done [here](https://github.com/jjeising/framework/blob/crs-tools-tracker/Library/String.php#L105-L106). I think manual replacement was done, because ´intl´ transliterates _ü_ to _u_ instead of _ue_.
Currently we don't check the context (_Überwacher_ should transliterate to _Ueberwacher_, but _TÜV_ should transliterate to _TUEV_), but this seems a little more complex. A regular expression would probably help.

**Comment by jjeising** [comment]
Fixed [here](https://github.com/jjeising/framework/commit/fec5c112d9294b8682259be2fca21fd66e05d95c) and in 460d6d3.
