### ISSUE TITLE
Create child tickets in trigger

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#90]
*Issue migrated from trac ticket # 90*

**component:** database | **priority:** major

#### 2014-10-20 16:01:11: @jjeising created the issue

___
With recent changes it's not possible nor useful anymore to create meta tickets without children. We should

1. Change create_missing_encoding_tickets to also depend on an encoding_profile_id
2. Change create_missing_recording_tickets(project_id) to create_missing_recording_ticket(ticket_id)
3. Check for an ingest ticket in create_missing_recording_ticket
4. Use these functions as a trigger when creating meta tickets (recording) or changing encoding profiles on a project (encoding).
5. Remove use of these functions from the application

**Comment by jjeising** [comment]
@a-tze We should reevaluate the need and current state here.

**Comment by pegro** [comment]
When we touch this, I would vote for a flag "create_ticket_via_trigger" on encoding profiles assigned to the project. For the encoding "cloud" of FeM we use a single tracker project for various encodings, where we only need a selection of the assigned profiles most of the time. 

So I'd like to be able to mark encoding profiles of which child tickets get created.

**Comment by a-tze** [comment]
So you have a certain project and don't want to have all encoding profiles for each ticket? If encoding tickets are not created automatically, which other possibility does the user have to create it?

Maybe a project-wide flag "auto-create (encoding) children" is sufficient?

**Comment by pegro** [comment]
Right now he can use RPC call createEncodingTicket, which for now never creates one, instead only return the already existing one.
For Webapp users a "create encoding ticket" page with a dropdown/checkbox list of available profiles might be useful.

Sure, a project-wide flag would also help. But you already can delete meta and encoding ticket, but only create meta tickets manually. Why not also allowing to create encoding ticket manually?!

**Comment by a-tze** [comment]
I'm not against allowing manual creation of encoding tickets. I only wanted to point out the contradiction to the current logic "always create children for all encoding profiles in project". So if we introduce a flag on the project to stop this automatic creation, the manual creation is of course the second half of the solution.

**Comment by a-tze** [comment]
> Right now he can use RPC call createEncodingTicket, which for now never creates one, instead only return the already existing one.

@pegro I had a look into this and want to fix it. Beside some constraint violations there is an unlucky mixup of encoding profile and encoding profile version. The getEncodingProfile call actually returns the versions of a project, and this is also checked at the beginning of the RPC handler method. The database function however wants to have the profile id instead of a version id. I'd change that, but need to know how breaking that change is.

If you say this all makes sense, I'd like to prepare a branch for review.

**Comment by pegro** [comment]
I'm not sure I can follow.

getEncodingProfiles returns a list of encoding profiles. EncodingProfileVersion is joined with EncodingProfile, so you get the columns of the assigned version and all columns of the profile.
On the client I use encoding_profile_id.

**Comment by a-tze** [comment]
I imagine a client would do the following:

call this https://github.com/crs-tools/tracker/blob/master/src/Application/Controller/XMLRPC/Handler.php#L148

which returns profiles. Choose magically what is to be done and then call 
https://github.com/crs-tools/tracker/blob/master/src/Application/Controller/XMLRPC/Handler.php#L346

and now when I look into it again, it's possibly just a mistake here:
https://github.com/crs-tools/tracker/blob/master/src/Application/Controller/XMLRPC/Handler.php#L381
where it should give the profile version id instead of the profile id...

does it make sense? Will try to change that line and test it again (I'm currently working up the rpc-test.pl script).

**Comment by pegro** [comment]
> where it should give the profile version id instead of the profile id...
Right now it doesn't make a huge difference. The DB function create_missing_encoding_ticket will derive the relevant profile version from the project the meta ticket is assigned to for the given encoding profile.

I don't really care for the actual version in the client. It's like that now because in the Project model, there were no means to just get encoding profiles assigned to the project, only versions.

**Comment by a-tze** [comment]
Sorry I misread your previous comment. 
The method name is still confusing, maybe there should be a transition from getEncodingProfiles to getEncodingProfileVersions to make that more clear.

Back to the original topic: having a flag "auto-create encoding tickets" sounds like a good idea.

What about the current implementations that use the encoding ticket creation via API, what do they do with recording tickets?

**Comment by pegro** [comment]
> The method name is still confusing, maybe there should be a transition from getEncodingProfiles to getEncodingProfileVersions to make that more clear.

The issue I have with this, is that this function doesn't return multiple versions of profiles, but just the list of profiles, each in the version assigned to the given project. I kind of want to hide the technical aspect of versions at all to the API users.

> What about the current implementations that use the encoding ticket creation via API, what do they do with recording tickets?

In our application we don't use recording tickets at all, so their existence or non-existence is irrelevant.
So we wouldn't mind having recording tickets created automatically. We won't just use them.

**Comment by jjeising** [comment]
> In our application we don't use recording tickets at all, so their existence or non-existence is irrelevant.
> So we wouldn't mind having recording tickets created automatically. We won't just use them.

In case we have a project flag *auto-create encoding tickets* we could easily add *auto-create recording/ingest tickets*. This seems more consistent.

**Comment by pegro** [comment]
## Auto-create ticket flag
But then we're talking about a single flag on a project. Not a flag on a encoding-profile-to-project-assignment?!

I would separate between a) recording and b) encoding tickets.
For a) there is no API to create them (yet), so the only way to have them right now is to auto-create them.
For b) there is API and I would prefer having a flag on each assigned encoding profile, whether encoding tickets for this should be created or not.

I use-case I could think of would be: you create a fancy new test encoding profile and want to test that on only a few selected tickets. Right now, if you assign that profile to the project, on the next import (or other actions) _createMissingEncodingTickets_ is called and you have tickets for that profile everywhere, which you might not want.
If you just have a global flag, then the usual import workflow doesn't work anymore, since no tickets get created. If I'm not mistaken.

## create_missing_encoding_tickets
The DB function _create_missing_encoding_tickets_ is never called with a encoding_profile_id in the whole code base.

Also when fixing the RPC method to allow creating more than just the missing encoding tickets, the DB function _create_missing_encoding_ticket_ gets obsolete.
